# writer
from_saved: ''

# optimizer
device: 'cuda'
epochs: 1000
episodes: 1  # iterations over same minibatch of graphs
max_iterations: 1

OPTIM: 'Adam'
OPTIM_lr: [0.001, 0.0003]
OPTIM_weight_decay: 0
OPTIM_stopping_patience: 5

batch_size: 128
pos_class_weight: 16.63 # (329782-18707)/18707 = 16.288   # (223969, 13135, 17.051313285116102)
#  weight_decay: 0.0001
feature_dropout: 0

# Task head:
H: ''
H_pool: 'sum'

# GCN
GNN: 'BareboneGIN'
global_hidden_channels: 128
GNN_dropout: [0,.3, .5]
GNN_num_layers: [2,3,4]


# GraphStructureLearner
GSL: 'GraphStructureLearner'
GSL_num_heads: 4
GSL_attention_threshold: 0.2  # positive  
GSL_graph_regularization: True
GSL_sparsity_ratio: 0.05
GSL_skip_ratio: 0.4  # lambda in GraphGLOW, percentage of using initial adjacency matrix
GSL_converged_threshold: 0.002
# Dataset
DS_root: 'codegraphs/diversevul/v2_directed_withdegreecount'  # folder with .pt pyg data objects
DS_filtertype: 'larger10smaller1000' # all, larger10smaller1000, larger10, smaller1000
DS_crossval: True
DS_folds: 5 # don't change
DS_cv_trainfraction: 0.20  # only use x*100 % of the training data of training folds
DS_cv_valfraction: 1  # only use x*100 % of the validation data of training folds
DS_nodeg: True