# writer
from_saved: ''

# optimizer
device: 'cuda'
epochs: 1000
episodes: 1  # iterations over same minibatch of graphs
max_iterations: [1,5]
profile: False

OPTIM: 'Adam'
OPTIM_lr: 0.001
OPTIM_weight_decay: 0
OPTIM_stopping_patience: 5
batch_size: 32
loader_batch_size: 16  # actual size for memory contstraint
pos_class_count: 11279
neg_class_count: 204557
#  weight_decay: 0.0001
feature_dropout: 0

# Task head:
H: 'BinaryClassifierReadOutLayerDense'
H_pool: 'sum'

# GCN
GNN: 'GCN'
global_hidden_channels: 128
GNN_dropout: 0.3
GNN_num_layers: 2


# GraphStructureLearner
GraphGLOW_only_enabled: True
GSL: 'GraphStructureLearner'
GSL_num_heads: 4
GSL_attention_threshold: 0.3  # positive
GSL_graph_regularization: True #[True, False]
GSL_sparsity_ratio: [0.0,0.2,0.4]
GSL_skip_ratio: [0.0, 0.3, 0.7]  # lambda in GraphGLOW, percentage of using initial adjacency matrix
GSL_converged_threshold: 0.002 
GSL_resethead: 0
GSL_mixed_precision: False  # only works for Structure Learner, not implemented for normal gnn

# Dataset
DS_root: 'codegraphs/diversevul/v2_undirected_withdegreecount'  # folder with .pt pyg data objects
DS_filtertype: 'larger10smaller1000' # all, larger10smaller1000, larger10, smaller1000
DS_crossval: True
DS_folds: 5 # don't change
DS_cv_trainfraction: 0.2  # only use x*100 % of the training data of training folds
DS_cv_valfraction: 1  # only use x*100 % of the validation data of training folds
DS_dense_mode: True